# Derived from mocks_bao/baseline/fits/lyaxlya.ini; native source is unchanged.
[data]
name = lyaxlya
tracer1 = LYA
tracer2 = LYA
tracer1-type = continuous
tracer2-type = continuous
base = /home/jchaves/Proyectos/projects/lya/data/mocks_bao/
filename = %(base)s/baseline/correlations/cf_lya_lya_0_10-exp.fits.gz
distortion-file = %(base)s/baseline/correlations/dmat_lya_lya_0_10.fits
weights-tracer1 = %(base)s/baseline/deltas_lya/Log/delta_attributes.fits.gz
weights-tracer2 = %(base)s/baseline/deltas_lya/Log/delta_attributes.fits.gz
zmin = 0.0
zmax = 10.0

[cuts]
rp-min = -300
rp-max = +300.
rt-min = 0
rt-max = 300.
r-min = 30
r-max = 180
mu-min = -1
mu-max = 1

[model]
z evol LYA = bias_vs_z_std
use_metal_autos = True
model-hcd = Rogers2018
fast_metals = True
single-metal-beta = True
new_metals = True
rp_only_metal_mats = False
marginalize-all-rmin-cuts = False
skip-nl-model-in-peak = True
fullshape smoothing = gauss
small scale nl = forestflow

[metals]
filename = None
z evol = bias_vs_z_std
in tracer1 = SiII(1260) SiIII(1207) SiII(1193) SiII(1190)
in tracer2 = SiII(1260) SiIII(1207) SiII(1193) SiII(1190)
fullshape smoothing = gauss

[metal-matrix]
rebin_factor = 3
alpha_LYA = 2.9
alpha_SiII(1260) = 1.
alpha_SiIII(1207) = 1.
alpha_SiII(1193) = 1.
alpha_SiII(1190) = 1.
alpha_CIV(eff) = 0.
z_ref_objects = 2.25
z_evol_objects = 1.44
z_bins_objects = 1000
